// learning-doc/src_legacy/components/common/footer.tsx
"use client";

import { Facebook, Github, Youtube } from "lucide-react";
import Link from "next/link";

import { cn } from "../../lib/utils";
import { Button } from "../custom/button";
import { useTranslation } from "react-i18next";

export function Footer({ className }: { className?: string }) {
  const { t } = useTranslation();
  return (
    <footer className={cn("border-t bg-background mt-12", className)}>
      <div className="max-w-6xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 gap-8 md:grid-cols-4">
          {/* Brand Section */}
          <div className="space-y-4">
            <Link href="/" className="flex items-center gap-2">
              <span className="text-lg font-semibold text-foreground">
                Emi
              </span>
            </Link>
            <p className="text-sm text-muted-foreground">
              {t("footer.description")}
            </p>
            <div className="flex space-x-2">
              <a href="https://www.facebook.com/khieu.dv96" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                  <Facebook className="h-4 w-4" />
                  <span className="sr-only">Facebook</span>
                </Button>
              </a>
              <a href="https://www.youtube.com/@vie-vlogs" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                  <Youtube className="h-4 w-4" />
                  <span className="sr-only">YouTube</span>
                </Button>
              </a>
              <a href="https://github.com/khieu-dv" target="_blank" rel="noopener noreferrer">
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                  <Github className="h-4 w-4" />
                  <span className="sr-only">GitHub</span>
                </Button>
              </a>
            </div>
          </div>

          {/* Posts Section */}
          <div>
            <h3 className="mb-3 text-sm font-medium text-foreground">{t("footer.posts")}</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link
                  href="/docs"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  {t("footer.allPosts")}
                </Link>
              </li>
              <li>
                <Link
                  href="/docs"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  {t("footer.goCourse")}
                </Link>
              </li>
              <li>
                <Link
                  href="/docs"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  {t("footer.ginCourse")}
                </Link>
              </li>
            </ul>
          </div>

          {/* Community Section */}
          <div>
            <h3 className="mb-3 text-sm font-medium text-foreground">{t("footer.community")}</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link
                  href="/chat"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  {t("footer.chatWithUs")}
                </Link>
              </li>
              <li>
                <Link
                  href="/docs"
                  className="text-muted-foreground hover:text-foreground transition-colors"
                >
                  {t("footer.discussions")}
                </Link>
              </li>
            </ul>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="mt-8 pt-6 border-t">
          <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
            <p className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} Emi. {t("footer.allRightsReserved")}
            </p>
            <div className="flex items-center gap-4 text-sm">
              <Link href="/privacy" className="text-muted-foreground hover:text-foreground transition-colors">
                {t("footer.privacy")}
              </Link>
              <Link href="/terms" className="text-muted-foreground hover:text-foreground transition-colors">
                {t("footer.terms")}
              </Link>
              <Link href="/contact" className="text-muted-foreground hover:text-foreground transition-colors">
                {t("footer.contact")}
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// learning-doc/components/common/Footer.vue
<script setup lang="ts">
import { BookOpen, Github, MessageCircle } from "lucide-vue-next";

const year = new Date().getFullYear();
</script>

<template>
    <footer class="mt-auto bg-[rgb(var(--color-bg-soft))] border-t border-[rgb(var(--color-border))]">
        <div class="container py-14">
            <div class="grid grid-cols-1 gap-10 md:grid-cols-4">
                <!-- Brand -->
                <div class="space-y-3 md:col-span-1">
                    <NuxtLink to="/" class="inline-flex items-center gap-2.5">
                        <div class="flex items-center justify-center w-7 h-7 rounded-md bg-[rgb(var(--color-accent-blue))] text-white">
                            <BookOpen :size="15" />
                        </div>
                        <span class="text-lg font-black tracking-tight text-[rgb(var(--color-text))]">
                            Journey Doc
                        </span>
                    </NuxtLink>
                    <p class="text-xs leading-relaxed text-[rgb(var(--color-text-soft))] max-w-xs">
                        High-density software engineering curricula covering Systems, Distributed Backends, Frontend Architecture, and CS Fundamentals.
                    </p>
                </div>

                <!-- Resources -->
                <div>
                    <h3 class="mb-3 text-xs font-bold text-[rgb(var(--color-text))] uppercase tracking-wider">
                        Resources
                    </h3>
                    <ul class="space-y-2">
                        <li>
                            <NuxtLink to="/courses"
                                class="text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                All Courses
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/courses/rust/lesson_0"
                                class="text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                Rust
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/courses/golang/lesson_0"
                                class="text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                Go
                            </NuxtLink>
                        </li>
                    </ul>
                </div>

                <!-- Community -->
                <div>
                    <h3 class="mb-3 text-xs font-bold text-[rgb(var(--color-text))] uppercase tracking-wider">
                        Community
                    </h3>
                    <ul class="space-y-2">
                        <li>
                            <a href="https://github.com" target="_blank" rel="noopener"
                                class="inline-flex items-center gap-1.5 text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                <Github :size="13" />
                                GitHub
                            </a>
                        </li>
                        <li>
                            <a href="#"
                                class="inline-flex items-center gap-1.5 text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                <MessageCircle :size="13" />
                                Discord
                            </a>
                        </li>
                    </ul>
                </div>

                <!-- Legal -->
                <div>
                    <h3 class="mb-3 text-xs font-bold text-[rgb(var(--color-text))] uppercase tracking-wider">
                        Legal
                    </h3>
                    <ul class="space-y-2">
                        <li>
                            <NuxtLink to="/privacy"
                                class="text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                Privacy Policy
                            </NuxtLink>
                        </li>
                        <li>
                            <NuxtLink to="/terms"
                                class="text-xs text-[rgb(var(--color-text-soft))] hover:text-[rgb(var(--color-accent-blue))] transition-colors">
                                Terms of Service
                            </NuxtLink>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Bottom Bar -->
            <div class="mt-12 pt-6 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-[rgb(var(--color-border))] text-xs text-[rgb(var(--color-text-soft))]">
                <p>&copy; {{ year }} Journey Doc. All rights reserved.</p>
                <p>Built with Nuxt 4 &amp; Vue 3</p>
            </div>
        </div>
    </footer>
</template>
