// learning-doc/components/custom/TipItem.vue
<script setup lang="ts">
import { CheckCircle2 } from "@lucide/vue";

defineProps<{
    title: string;
    description: string;
}>();
</script>

<template>
    <div
        class="flex gap-4 p-6 bg-white dark:bg-slate-900 rounded-3xl ring-1 ring-slate-100 dark:ring-slate-800 shadow-sm transition-all hover:shadow-md">
        <div
            class="flex-shrink-0 w-8 h-8 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-600">
            <CheckCircle2 :size="20" />
        </div>
        <div class="space-y-1">
            <h4 class="font-bold text-slate-900 dark:text-white">{{ title }}</h4>
            <p class="text-sm text-muted-foreground leading-relaxed">
                {{ description }}
            </p>
        </div>
    </div>
</template>

// learning-doc/src_legacy/components/custom/tip-item.tsx
"use client";

import { useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';

type TipItemProps = {
  title: string;
  description: string;
};

export function TipItem(props: TipItemProps) {
  const { title, description } = props;
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="border-b border-gray-100 last:border-0 dark:border-gray-800">
      <button
        className="flex w-full items-center justify-between py-3 text-left transition-colors hover:bg-gray-50 dark:hover:bg-slate-800"
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <span className="font-medium text-gray-900 dark:text-white">{title}</span>
        {isExpanded ? (
          <ChevronUp className="h-5 w-5 text-gray-500" />
        ) : (
          <ChevronDown className="h-5 w-5 text-gray-500" />
        )}
      </button>
      {isExpanded && (
        <div className="pb-3">
          <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">{description}</p>
        </div>
      )}
    </div>
  );
}
